apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: practice
  region: us-east-1

managedNodeGroups:
  - name: expense
    instanceType:
      - t3.medium
      - t3.large
      - m5.large
      - m5a.large  
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    spot: true