apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: practice
  region: us-west-2

managedNodeGroups:
  - name: expense
    instanceType: t3.medium   
    desiredCapacity: 2
    minSize: 1
    maxSize: 2